# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GITHUB_USERNAME: ${{ secrets.PROJECT_GITHUB_USERNAME }}
      GITHUB_API_TOKEN: ${{ secrets.PROJECT_GITHUB_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run coverage
        run: |
          poetry run coverage run --source=vulcanbox --omit="*/__*.py,*/test_*.py" -m pytest

      - name: Generate report
        run: |
          poetry run coverage report -m > coverage.txt

      - name: Create GHA job summary
        if: always()
        run: |
          echo "### Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo '```shell' >> $GITHUB_STEP_SUMMARY
          cat coverage.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
