name: Docker Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        with:
          version: "latest"

      - name: Build Docker image
        run: |
          docker build -t vulcanbox-cli .

      - name: Run Docker container
        run: |
          docker run --name vulcanbox-container -d vulcanbox-cli
          sleep 5

      - name: Test Docker CLI
        run: |
          docker exec vulcanbox-container vulcanbox --help

      - name: Clean up
        run: |
          docker stop vulcanbox-container
          docker rm vulcanbox-container
