name: Docker Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        with:
          version: "latest"

      - name: Build Docker image
        run: |
          docker build -t vulcanbox .
          sleep 3
          docker image ls

      - name: Run CLI Docker image
        run: |
          docker run --rm vulcanbox --version

      - name: Clean up
        run: |
          TARGET=$(docker images | grep "vulcanbox" | awk "{print \$3}")
          docker rmi "${TARGET}"
